services:

  front1:
    image: messanger-nginx:0.1
    build: frontend
    volumes:
      - "./nginx/default1.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./frontend/dist/:/usr/share/nginx/html"
    ports:
      - "8001:80"

  front2:
    image: messanger-nginx:0.1
    build: frontend
    volumes:
      - "./nginx/default2.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./frontend/dist/:/usr/share/nginx/html"
    ports:
      - "8002:80"

  back-1:
    build: .
    image: messanger:0.1
    environment:
      REDIS_CACHE_URL: redis://redis:6379/0
      BROADCAST_TYPE: redis
      BROADCAST_REDIS_URL: redis://redis:6379/0
    volumes:
      - "./db.sqlite3:/app/db.sqlite3"

  back-2:
    build: .
    image: messanger:0.1
    environment:
      REDIS_CACHE_URL: redis://redis:6379/0
      BROADCAST_TYPE: redis
      BROADCAST_REDIS_URL: redis://redis:6379/0
    volumes:
      - "./db.sqlite3:/app/db.sqlite3"

  redis:
    image: redis:7.4-alpine
