[tool.poetry]
name = "messanger"
version = "0.1.0"
description = ""
authors = ["ig-rudenko <ig.rudenko1@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.2"
uvicorn = "^0.31.1"
pydantic-settings = "^2.5.2"
redis = "^5.1.1"
websockets = "^13.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = "^1.7.4"
alembic = "^1.13.3"
aiosqlite = "^0.20.0"
pydantic = {extras = ["email"], version = "^2.9.2"}
bcrypt = "^4.2.0"


[tool.poetry.group.dev.dependencies]
black = {extras = ["d"], version = "^24.10.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
