"""messages

Revision ID: 1e875d42121e
Revises: d9840d471c35
Create Date: 2024-10-16 11:21:32.736394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e875d42121e'
down_revision: Union[str, None] = 'd9840d471c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__messages'))
    )
    op.create_index(op.f('ix__messages__created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix__messages__recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix__messages__sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__messages__sender_id'), table_name='messages')
    op.drop_index(op.f('ix__messages__recipient_id'), table_name='messages')
    op.drop_index(op.f('ix__messages__created_at'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
